export const labels = {
  common: {
    hubik: 'Hubik',
    tagline: 'Hubik Real Estate AI',
    back: 'Regresar',
    menu: 'Menú de opciones',
    todayTime: 'Hoy, 10:30',
    understood: 'Entendido',
  },
  chat: {
    inputPlaceholder: 'Escriba su consulta aquí...',
    accessibilityInput: 'Campo de consulta inmobiliaria',
    stopRecordingA11y: 'Detener grabación de nota de voz',
    sendQueryA11y: 'Enviar consulta',
    micA11y: 'Hablar por micrófono',
    sendSrOnly: 'Enviar',
    propertiesFound: (count: number) => `Propiedades Encontradas (${count}):`,
    justNow: 'Ahora',
    typing: 'Hubik está escribiendo…',
    voiceNote: '🎤 Nota de voz',
    registerExample:
      '¡Hola! Cuénteme la propiedad con sus propias palabras: tipo, si es venta o alquiler, precio, habitaciones, baños, metros y ubicación. También puede adjuntar fotos y marcar el mapa con los botones de abajo, cuando quiera.',
    cancelRegistrationConfirmation:
      'De acuerdo, cancelé el registro. Puede volver a intentarlo cuando quiera.',
    publishedSuccess: (title: string) => `¡Listo! Publiqué "${title}" en Hubik.`,
    publishError: (err: string) =>
      `⚠️ No pude publicar la propiedad (${err}). Sus datos siguen guardados, puede intentar de nuevo.`,
    photosPrompt:
      '¿Desea agregar o cambiar las fotos de la propiedad? Diga "adjuntar fotos", o "continuar" para mantener las que tiene.',
    photosContinueLocationPrompt:
      'Perfecto. Ahora diga o escriba "fijar ubicación" o "abrir mapa" para marcar en el mapa dónde está la propiedad.',
    photosPermissionRequired:
      'Necesito permiso para acceder a sus fotos. Actívelo desde los ajustes del dispositivo para adjuntar imágenes, o diga "continuar sin fotos".',
    photosAdded: (added: number, total: number) =>
      `Añadí ${added} foto(s). Tiene ${total} en total (se subirán al publicar). Puede decir o escribir "continuar" para seguir con el registro, o agregar más fotos.`,
    photosNoneSelected:
      'No se seleccionó ninguna foto. Puede intentarlo de nuevo o decir "continuar sin fotos".',
    photosSelectionError: (err: string) =>
      `⚠️ No pude seleccionar esas fotos (${err}). Intente de nuevo.`,
    correctionPrompt: '¿Qué dato desea corregir? Cuéntemelo y lo actualizo.',
    confirmDataPrompt: (summary: string) =>
      `${summary}\n\n¿Los datos son correctos? Diga o escriba "confirmar" o "publicar" para publicarla, o indíqueme qué desea corregir.`,
    askPhotosPrompt: (max: number) =>
      `¿Desea agregar fotos de la propiedad? Puede decir "adjuntar fotos" (hasta ${max}), o decir "continuar sin fotos" para seguir adelante.`,
    processDataError: (err: string) =>
      `⚠️ No pude procesar esos datos (${err}). Intente nuevamente.`,
    serviceError: (err: string) =>
      `⚠️ No se pudo conectar con el servicio de IA (${err}). Por favor intenta nuevamente.`,
    voiceProcessError: (err: string) =>
      `⚠️ No pude procesar la nota de voz (${err}). Intenta grabar de nuevo o escribir tu mensaje.`,
    locationConfirmedNotice: (address: string) =>
      `📍 Ubicación confirmada: ${address}. Generando la descripción de la propiedad...`,
    previewSummary: (summary: string) =>
      `¡Listo! Aquí tiene la vista previa. Puede editar cualquier dato antes de publicar.\n\n${summary}\n\n¿Los datos son correctos? Diga o escriba "confirmar" o "publicar" para publicarla, o indíqueme qué desea corregir.`,
    descriptionGenError: (err: string) =>
      `⚠️ No pude generar la descripción (${err}). Diga o escriba "fijar ubicación" para intentar de nuevo.`,
    micNotAvailableTitle: 'Micrófono no disponible',
    voiceNoteFailedTitle: 'No pudimos entender la nota de voz',
    voiceNoteFailedMessage: 'Inténtelo de nuevo o escriba su consulta.',
    micNotAvailableMessage:
      'No pudimos acceder al micrófono. Revisa los permisos de la app o escribe tu mensaje.',
    attachMorePhotos: 'Adjuntar más fotos',
  },
  propertyCard: {
    ownListing: 'Tuya',
    status: {
      available: 'Disponible',
      pending: 'Pendiente',
      sold: 'Vendido',
    },
    commission: '',
    photosCount: (count: number) => `${count} fotos`,
    defaultPhotosCount: '14 fotos',
    exteriorElevator: ' · Exterior con ascensor',
    sqmLabel: (sqm: number | string) => `${sqm} metros cuadrados`,
    sqmSuffix: 'm²',
    studio: 'Estudio',
    bedroomShort: (count: number) => `${count} hab.`,
    bathrooms: (count: number) => (count === 1 ? '1 baño' : `${count} baños`),
    viewDetails: 'Ver detalle',
    share: 'Compartir',
    viewDetailsA11y: (title: string) => `Ver detalle de ${title}`,
    shareA11y: (title: string) => `Compartir ${title}`,
    shareMessage: (title: string, price: string, city: string, address: string | null) =>
      `Mira esta propiedad en Hubik: ${title} por ${price} en ${city}.${address ? `\nDirección: ${address}` : ''}`,
  },
  photoGrid: {
    add: 'Añadir',
    addA11y: 'Añadir más fotos',
    cover: 'Portada',
    removeA11y: (index: number) => `Eliminar foto ${index}`,
    moveBackA11y: (index: number) => `Mover foto ${index} hacia atrás`,
    moveForwardA11y: (index: number) => `Mover foto ${index} hacia adelante`,
  },
  mapPicker: {
    title: 'Fijar ubicación',
    closeA11y: 'Cerrar mapa',
    confirm: 'Confirmar ubicación',
    confirmA11y: 'Confirmar ubicación',
    loadingLocation: 'Detectando ubicación...',
  },
  livingDraft: {
    title: 'Ficha en progreso',
    sale: 'Venta',
    rent: 'Alquiler',
    bedroomShort: (count: number) => `${count} hab.`,
    bathrooms: (count: number) => `${count} baños`,
    sqmSuffix: (sqm: number | string) => `${sqm} m²`,
    completeFieldA11y: (fieldLabel: string) => `Completar ${fieldLabel}`,
    propertyTypeA11y: (option: string) => `Tipo de propiedad: ${option}`,
    operationTypeA11y: (option: string) => `Operación: ${option}`,
  },
  screenChat: {
    error: 'No pude completar eso. Inténtelo de nuevo.',
    viewConversation: 'Ver conversación',
    viewConversationA11y: 'Abrir la conversación completa',
    lastReplyA11y: (text: string) => `Última respuesta: ${text}`,
  },
  agencyChat: {
    help: 'Puedo ayudarle con su equipo. Diga, por ejemplo: "agrega a ana@correo.com como agente", "cancela la invitación de luis@correo.com", "¿cuántos agentes tengo?" o "vuelve al inicio".',
    askEmail: 'Escriba el correo del agente, por ejemplo: agrega a ana@correo.com como agente.',
    inviteCancelled: (email: string) => `Listo. Cancelé la invitación de ${email}.`,
    inviteNotFound: (email: string) => `No encuentro una invitación pendiente para ${email}.`,
    teamLoading: 'Todavía estoy cargando su equipo. Inténtelo en un momento.',
    teamCount: (agents: number, invites: number) =>
      `Tiene ${agents} ${agents === 1 ? 'agente' : 'agentes'} y ${invites} ${invites === 1 ? 'invitación pendiente' : 'invitaciones pendientes'}.`,
    teamAgents: (names: string[]) => `Sus agentes: ${names.join(', ')}.`,
    teamInvites: (emails: string[]) => `Invitaciones pendientes: ${emails.join(', ')}.`,
    goingHome: 'De acuerdo, vuelvo al inicio.',
  },
  gallery: {
    openA11y: (count: number) => `Ver todas las fotos (${count})`,
    closeA11y: 'Cerrar las fotos',
    counter: (index: number, count: number) => `${index} de ${count}`,
    photoA11y: (index: number, count: number) => `Foto ${index} de ${count}`,
    thumbnailA11y: (index: number, count: number) => `Ir a la foto ${index} de ${count}`,
    previousA11y: 'Foto anterior',
    nextA11y: 'Foto siguiente',
  },
  sharedProperty: {
    brand: 'Hubik',
    loading: 'Cargando la propiedad…',
    notFoundTitle: 'Esta propiedad ya no está disponible',
    notFoundMessage: 'Puede que el enlace sea incorrecto o que la propiedad se haya retirado.',
    error: 'No pudimos cargar la propiedad.',
    retry: 'Reintentar',
    descriptionTitle: 'Descripción',
    seo: {
      siteName: 'Hubik',
      locale: 'es_ES',
      unavailableTitle: 'Propiedad no disponible · Hubik',
    },
    bedrooms: (count: number) => `${count} hab.`,
    bathrooms: (count: number) => `${count} ${count === 1 ? 'baño' : 'baños'}`,
    area: (count: number) => `${count} m²`,
    sheet: {
      title: 'Vea más propiedades en la app de Hubik',
      subtitle: 'Busque propiedades hablando o escribiendo, desde su móvil.',
      download: 'Descargar la app',
      comingSoon: 'Próximamente',
      continue: 'Seguir en el navegador',
      closeA11y: 'Cerrar la invitación a la app',
      downloadA11y: 'Descargar la app de Hubik',
      comingSoonA11y: 'La app de Hubik estará disponible próximamente',
      openApp: 'Abrir en la app',
      openAppA11y: 'Abrir este anuncio en la app de Hubik',
      openFailed: '¿No se abrió? Puede que todavía no tenga la app instalada.',
    },
    bar: {
      text: 'Hubik · Mejor en la app',
      cta: 'Descargar',
      ctaA11y: 'Ver cómo descargar la app de Hubik',
    },
  },
  slashMenu: {
    hints: {
      register: 'Publicar una propiedad',
      clear: 'Limpiar el historial del chat',
    },
    noCommandsNote: 'Los comandos están disponibles para agentes de una inmobiliaria',
    commandA11y: (command: string, hint: string) => `${command}, ${hint}`,
  },
  startScreen: {
    greeting: (name: string) => `Hola, ${name}`,
    greetingAnonymous: 'Bienvenido a Hubik',
    subtitles: {
      visitor: 'Encuentre su próxima vivienda',
      client: '¿Qué vivienda busca hoy?',
      agent: '¿Qué va a publicar o buscar hoy?',
      owner: 'Gestione su inmobiliaria y su equipo',
    },
    actionsTitle: 'Empezar',
    examplesTitle: 'Pruebe a decir…',
    micHint: 'Toque el micrófono para hablar',
    exampleA11y: (text: string) => `Probar: ${text}`,
    actionA11y: (title: string, subtitle: string) => `${title}. ${subtitle}`,
    actions: {
      search: { title: 'Buscar propiedades', subtitle: 'Vea lo que hay disponible' },
      sign_in: { title: 'Iniciar sesión', subtitle: 'Con Google o Apple' },
      register: { title: 'Publicar una propiedad', subtitle: 'Descríbala y suba fotos' },
      my_agency: { title: 'Mi inmobiliaria', subtitle: 'Agentes y propiedades' },
      create_agency: { title: 'Crear mi inmobiliaria', subtitle: 'Invite a sus agentes' },
    },
  },
  photoOrder: {
    title: 'Ordenar fotos',
    hint: 'Mantenga pulsada una foto y arrástrela. La primera es la portada.',
    cover: 'Portada',
    position: (index: number) => `Foto ${index}`,
    done: 'Listo',
    cancel: 'Cancelar',
    moveUpA11y: (index: number) => `Mover foto ${index} hacia arriba`,
    moveDownA11y: (index: number) => `Mover foto ${index} hacia abajo`,
    dragA11y: (index: number) => `Arrastrar la foto ${index}. Mantenga pulsado para moverla`,
  },
  composer: {
    alreadyComposing:
      'Ya estamos creando una propiedad. Puede seguir describiéndola, o escribir "cancelar" para empezar de nuevo.',
    publishConfirmTitle: '¿Publicar esta propiedad?',
    publishConfirmMessage: 'Se publicará con los datos, fotos y ubicación que ve en la ficha.',
    publishConfirmAction: 'Publicar',
    publishConfirmCancel: 'Revisar',
    photosFull: (max: number) => `Ya tiene el máximo de ${max} fotos.`,
    attachPhotosA11y: (count: number) => (count > 0 ? `Añadir fotos, ${count} añadidas` : 'Añadir fotos'),
    orderPhotos: 'Ordenar',
    orderPhotosA11y: 'Ordenar las fotos',
    pickLocationA11y: (hasPin: boolean) =>
      hasPin ? 'Cambiar ubicación en el mapa, ya marcada' : 'Marcar ubicación en el mapa',
    statusWords: {
      ok: 'Listo',
      missing: 'Falta',
      changed: 'Nuevo',
    },
    noValueA11y: 'sin dato',
    fieldRowA11y: (label: string, value: string, status: string) => `${label}: ${value}, ${status}. Toque para editar`,
    editInputA11y: (label: string) => `Editar ${label}`,
    editSave: 'Guardar',
    editCancel: 'Cancelar',
    panelProgress: (filled: number, total: number) => `${filled} de ${total} datos`,
    mediaStatus: (hasPhotos: boolean, hasPin: boolean) => {
      if (hasPhotos && hasPin) return 'Fotos y ubicación listas';
      if (hasPhotos) return 'Falta marcar la ubicación';
      if (hasPin) return 'Faltan fotos';
      return 'Faltan fotos y ubicación';
    },
    photoChipLabel: (count: number) => (count === 0 ? 'Añadir fotos' : count === 1 ? '1 foto' : `${count} fotos`),
    photoChipHint: (count: number) => (count === 0 ? 'Recomendado: 3 o más' : 'Toque para gestionar'),
    locationChipLabel: (hasPin: boolean) => (hasPin ? 'Ubicación marcada' : 'Marcar ubicación'),
    locationChipHint: (hasPin: boolean) => (hasPin ? 'Toque para cambiar' : 'Sin definir'),
    missingHint: (count: number) => (count === 1 ? 'Falta 1 dato' : `Faltan ${count} datos`),
    expandPanelA11y: 'Ver la ficha completa',
    collapsePanelA11y: 'Ocultar la ficha',
    publish: 'Publicar',
    publishing: 'Publicando…',
    preview: 'Vista previa',
    previewA11yReady: 'Ver cómo quedará el anuncio',
    previewA11yBlocked: 'Vista previa, no disponible hasta completar los datos',
    publishA11yReady: 'Publicar propiedad',
    publishA11yBlocked: (missingText: string) => `Publicar propiedad, no disponible. ${missingText}`,
    suggestionsTitle: 'Sugerencias',
    suggestions: {
      no_photos: 'Añada al menos 3 fotos para que el anuncio destaque.',
      few_photos: 'Añada más fotos: se recomiendan al menos 3.',
      no_pin: 'Marque la ubicación en el mapa para mostrar dónde está.',
      no_description: 'Redacte la descripción con IA para mejorar las búsquedas.',
      stale_description: 'Los datos cambiaron: regenere la descripción.',
      short_description: 'La descripción es corta: añada detalles como la luz, la orientación o el entorno.',
      no_amenities: 'Mencione las comodidades: piscina, garaje, ascensor…',
    },
    photosTitle: 'Fotos',
    pinTitle: 'Ubicación',
    pinSet: (latitude: number, longitude: number) => `Marcada: ${latitude.toFixed(4)}, ${longitude.toFixed(4)}`,
    pinNone: 'Aún sin marcar',
    pinMark: 'Marcar en el mapa',
    pinChange: 'Cambiar',
    pinChangeA11y: 'Cambiar ubicación',
    descriptionTitle: 'Descripción',
    descriptionPending: 'Se redactará sola cuando estén los datos principales.',
    descriptionWorking: 'Redactando la descripción…',
    descriptionFailed: 'No pude redactar la descripción. Puede reintentar o publicar sin ella.',
    descriptionGenerate: 'Redactar con IA',
    descriptionRegenerate: 'Regenerar descripción',
    descriptionRetry: 'Reintentar',
    fieldErrors: {
      required: 'Escriba un valor.',
      invalid_number: 'Escriba solo números.',
      not_integer: 'Use un número entero.',
      out_of_range: 'Ese valor está fuera de rango.',
      too_long: 'Es demasiado largo.',
      invalid_catastro: 'La referencia catastral debe tener entre 14 y 20 letras y números.',
      invalid_option: 'Elija una de las opciones.',
    },
  },
  amenitiesConfirmation: {
    title: 'Comodidades detectadas',
    empty: 'Aún no detecté comodidades. Puede agregarlas abajo.',
    addPlaceholder: 'Agregar comodidad o característica...',
    addA11y: 'Agregar comodidad',
    removeA11y: (amenity: string) => `Quitar ${amenity}`,
  },
  burgerMenu: {
    brandTitle: 'Hubik',
    closeA11y: 'Cerrar menú lateral',
    backdropA11y: 'Cerrar menú',
    roleLabels: {
      client: 'Cliente',
      agent: 'Agente',
      owner: 'Propietario',
    },
    unnamedUser: 'Usuario',
    profileA11y: (name: string, role: string) => `${name}, ${role}`,
    guestTitle: 'Encuentra la propiedad de tus sueños',
    guestCta: 'Regístrate',
    guestA11y: 'Encuentra la propiedad de tus sueños. Regístrate o inicia sesión',
    version: 'Hubik Real Estate AI • v1.0',
    menuItems: {
      search: 'Buscar Propiedades',
      register: 'Registrar Vivienda',
      newChat: 'Reiniciar Chat',
      badgeNew: 'Nuevo',
      signIn: 'Iniciar sesión',
      signOut: 'Cerrar sesión',
      createAgency: 'Tengo una inmobiliaria',
      myAgency: 'Mi inmobiliaria',
    },
  },
  auth: {
    signInTitle: 'Bienvenido a Hubik',
    signInSubtitle:
      'Inicie sesión para publicar propiedades o crear su inmobiliaria. Para buscar propiedades no necesita cuenta.',
    continueWithGoogle: 'Continuar con Google',
    continueWithApple: 'Continuar con Apple',
    continueWithoutAccount: 'Seguir buscando sin cuenta',
    signingIn: 'Iniciando sesión...',
    signInError: (err: string) =>
      `No pudimos iniciar sesión (${err}). Inténtelo de nuevo.`,
    signOutErrorTitle: 'No se pudo cerrar la sesión',
    signOutErrorMessage: 'Compruebe su conexión e inténtelo de nuevo.',
    signInStartError: 'No se pudo iniciar el proceso de inicio de sesión.',
    signInMissingCodeError: 'El proveedor no devolvió un código de acceso válido.',
    agencyNameRequired: 'Escriba el nombre de la inmobiliaria (mínimo 2 letras).',
    createAgencyTitle: 'Cree su inmobiliaria',
    createAgencySubtitle:
      'Será el propietario de la inmobiliaria. Un miembro del equipo de Hubik asignará a sus agentes.',
    agencyNameLabel: 'Nombre de la inmobiliaria',
    agencyNamePlaceholder: 'Por ejemplo: Inmobiliaria Casa Norte',
    createAgencySubmit: 'Crear inmobiliaria',
    createAgencySubmitting: 'Creando...',
    createAgencyError: (err: string) =>
      `No pudimos crear la inmobiliaria (${err}). Inténtelo de nuevo.`,
    createAgencySuccess: 'Inmobiliaria creada.',
    signInRequiredForAgency: 'Inicie sesión para crear su inmobiliaria.',
    myAgencyTitle: 'Mi inmobiliaria',
    myAgencyEmpty: 'Sus agentes aún no han publicado propiedades.',
    myAgencyLoadError: 'No pudimos cargar las propiedades de su inmobiliaria.',
    retry: 'Reintentar',
    registerRequiresSignIn:
      'Para registrar una propiedad, inicie sesión con su cuenta de agente desde el menú.',
    registerRequiresAgent:
      'Solo los agentes de una inmobiliaria pueden registrar propiedades. Si es agente, pida a su inmobiliaria que le asigne.',
    listedBy: (agency: string, agent?: string | null) =>
      agent ? `${agency} · ${agent}` : agency,
    back: 'Regresar',
    agents: {
      sectionTitle: 'Agentes',
      sectionSubtitle:
        'Agregue el correo de cada agente. Si todavía no usa Hubik, será agente en cuanto inicie sesión con ese correo.',
      emailLabel: 'Correo del agente',
      emailPlaceholder: 'agente@correo.com',
      addButton: 'Agregar',
      addingButton: 'Agregando...',
      listTitle: 'Su equipo',
      emptyList: 'Todavía no tiene agentes.',
      agentRole: 'Agente',
      pending: 'Pendiente',
      unnamedAgent: 'Agente sin nombre',
      cancelInvite: 'Cancelar',
      cancelInviteA11y: (email: string) => `Cancelar la invitación de ${email}`,
      agentRowA11y: (name: string) => `${name}, agente`,
      inviteRowA11y: (email: string) => `${email}, invitación pendiente`,
      loadError: 'No pudimos cargar sus agentes.',
      search: {
        hint: 'También puede escribir el nombre de un cliente para buscarlo.',
        searching: 'Buscando…',
        noResults: 'Sin coincidencias. Puede invitar con el correo completo.',
        rateLimited: 'Demasiadas búsquedas. Espere un momento e inténtelo de nuevo.',
        error: 'No pudimos buscar. Puede escribir el correo completo.',
        unnamedClient: 'Cliente sin nombre',
        resultA11y: (name: string, maskedEmail: string) => `Elegir a ${name}, ${maskedEmail}`,
        selectedTitle: 'Persona elegida',
        selectedA11y: (name: string, maskedEmail: string) => `${name}, ${maskedEmail}, elegida`,
        change: 'Cambiar',
        changeA11y: 'Elegir a otra persona',
      },
      feedback: {
        agent_added: 'Listo. Esta persona ya es agente de su inmobiliaria.',
        invited: 'Invitación guardada. Será agente en cuanto inicie sesión con ese correo.',
        already_listed: 'Este correo ya está en su lista.',
        unavailable: 'Este correo no se puede agregar.',
      },
      errors: {
        invalid_email: 'Escriba un correo válido, por ejemplo agente@correo.com.',
        generic: 'No pudimos completar la acción. Inténtelo de nuevo.',
        cancel: 'No pudimos cancelar la invitación. Inténtelo de nuevo.',
      },
    },
  },
  propertyDetail: {
    previewBanner: 'Vista previa: así verán su anuncio. Todavía no está publicado.',
    noAgencyFees: 'Sin honorarios de agencia',
    descriptionSectionTitle: 'Descripción de la vivienda',
    contactAdvisor: 'Contactar asesor',
    contactAdvisorA11y: 'Contactar asesor de Hubik',
    contactAdvisorAlertTitle: 'Contactar asesor',
    contactAdvisorAlertMessage:
      'Conectando con su asesor personal de Hubik para coordinar una visita accesible.',
    askAbout: (question: string, title: string) => `${question} (sobre «${title}»)`,
    errorGeneratingDescription: 'No se pudo generar la descripción en este momento.',
    featuresSectionTitle: 'Comodidades',
    operationSale: 'En venta',
    operationRent: 'En alquiler',
    approximateLocation: 'Ubicación aproximada',
    rentSuffix: '/mes',
    stats: {
      bedrooms: (value: string | number) => `${value} hab.`,
      bathrooms: (value: string | number) => `${value} baños`,
      squareMeters: (value: string | number) => `${value} m²`,
    },
    agentCard: {
      agencySubtitle: 'Inmobiliaria',
      agentSubtitle: 'Asesor asignado',
      contactPrompt: 'Gestionado por',
      cardA11y: (agency: string, agent?: string) =>
        agent ? `Inmobiliaria ${agency}, asesor ${agent}` : `Inmobiliaria ${agency}`,
    },
    photosCount: (current: number, total: number) => `1 de ${total} foto${total === 1 ? '' : 's'}`,
    noPhotos: 'Sin fotos',
    mockPhotosCount: '1 de 8 fotos',
  },
  notFound: {
    pageTitle: 'Oops!',
    message: "This screen doesn't exist.",
    homeLink: 'Go to home screen!',
  },
  suggestionChips: {
    searchForA11y: (chip: string) => `Search for ${chip}`,
  },
} as const;

export type Labels = typeof labels;
