import { Platform, StyleSheet } from 'react-native';
import { ThemeColors, shapes, spacing, typography } from '../../theme/colors';

export const getPropertyDetailStyles = (theme: ThemeColors) => ({
  styles: StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    container: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: spacing.marginMobile,
      paddingTop: 14,
      paddingBottom: 24,
    },
    previewBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: 12,
      marginBottom: 12,
      borderRadius: shapes.lg,
      backgroundColor: theme.secondaryContainer,
    },
    previewBannerText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '600',
      color: theme.onSecondaryContainer,
    },
    imageWrapper: {
      width: '100%',
      height: 240,
      borderRadius: shapes.xl,
      overflow: 'hidden',
      position: 'relative',
      marginBottom: 20,
      backgroundColor: theme.surfaceContainerHigh,
    },
    heroImage: {
      width: '100%',
      height: '100%',
    },
    photoCountBadge: {
      position: 'absolute',
      top: 14,
      right: 14,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.94)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: shapes.full,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 4,
      elevation: 3,
    },
    badgeIcon: {
      marginRight: 6,
    },
    photoCountText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.text,
    },
    priceLocationBlock: {
      marginBottom: 24,
    },
    priceText: {
      fontSize: 28,
      fontWeight: '800',
      letterSpacing: -0.5,
      marginBottom: 8,
      color: theme.primary,
    },
    agencyBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: shapes.sm,
      marginBottom: 16,
      backgroundColor: theme.secondaryContainer,
    },
    agencyBadgeText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.onSecondaryContainer,
    },
    locationRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    locationPin: {
      marginRight: 8,
      marginTop: 2,
    },
    locationTexts: {
      flex: 1,
    },
    neighborhoodTitle: {
      fontFamily: Platform.select({
        ios: 'Georgia',
        android: 'serif',
        default: 'serif',
      }),
      fontSize: 18,
      fontWeight: '700',
      marginBottom: 2,
      color: theme.text,
    },
    addressSubtitle: {
      fontSize: 14,
      lineHeight: 20,
      color: theme.textSecondary,
    },
    sectionContainer: {
      marginBottom: 26,
    },
    sectionTitle: {
      fontFamily: Platform.select({
        ios: 'Georgia',
        android: 'serif',
        default: 'serif',
      }),
      fontSize: 20,
      fontWeight: '700',
      letterSpacing: -0.3,
      marginBottom: 16,
      color: theme.primary,
    },
    gridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    featureCard: {
      width: '48%',
      borderRadius: shapes.lg,
      borderWidth: 1.5,
      padding: 16,
      marginBottom: 12,
      minHeight: 110,
      justifyContent: 'space-between',
      backgroundColor: theme.card,
      borderColor: theme.border,
    },
    featureIconBadge: {
      width: 36,
      height: 36,
      borderRadius: shapes.sm,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
      backgroundColor: theme.secondaryContainer,
    },
    featureTitle: {
      fontSize: 15,
      fontWeight: '700',
      marginBottom: 4,
      color: theme.text,
    },
    featureSubtitle: {
      fontSize: 13,
      lineHeight: 17,
      color: theme.textSecondary,
    },
    descriptionBlock: {
      paddingVertical: 4,
    },
    descriptionParagraph: {
      ...typography.bodyLG,
      fontSize: 16,
      lineHeight: 24,
      marginBottom: 14,
      color: theme.text,
    },
    descriptionParagraphSecondary: {
      ...typography.bodyLG,
      fontSize: 16,
      lineHeight: 24,
      marginBottom: 14,
      color: theme.textSecondary,
    },
    amenitiesCard: {
      borderRadius: shapes.xl,
      borderWidth: 1.5,
      padding: 18,
      backgroundColor: theme.card,
      borderColor: theme.border,
    },
    amenitiesTitle: {
      fontFamily: Platform.select({
        ios: 'Georgia',
        android: 'serif',
        default: 'serif',
      }),
      fontSize: 18,
      fontWeight: '700',
      marginBottom: 14,
      color: theme.primary,
    },
    amenitiesList: {
      width: '100%',
    },
    amenityRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
    },
    amenityBorder: {
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    amenityLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    amenityIcon: {
      marginRight: 12,
    },
    amenityName: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.text,
    },
    amenityDistance: {
      fontSize: 14,
      fontWeight: '500',
      marginLeft: 8,
      color: theme.textSecondary,
    },
    bottomDock: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      paddingHorizontal: spacing.marginMobile,
      paddingTop: 12,
      paddingBottom: 24,
      borderTopWidth: 1,
      shadowColor: '#02241F',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 8,
      backgroundColor: theme.background,
      borderTopColor: theme.outlineVariant,
    },
    contactButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      height: 52,
      borderRadius: shapes.lg,
      marginBottom: 10,
      backgroundColor: theme.primary,
    },
    contactIcon: {
      marginRight: 8,
    },
    contactButtonText: {
      fontSize: 16,
      fontWeight: '700',
      letterSpacing: 0.2,
      color: theme.onPrimary,
    },
    detailInputContainer: {
      paddingHorizontal: 0,
      paddingVertical: 0,
    },
  }),
  iconColor: theme.text,
  iconColorSecondary: theme.secondary,
  iconColorOnPrimary: theme.onPrimary,
  primaryColor: theme.primary,
});
