import { Platform, StyleSheet } from 'react-native';
import { ThemeColors, shapes, typography } from '../theme/colors';

export const getPropertyCardStyles = (theme: ThemeColors) => ({
  styles: StyleSheet.create({
    card: {
      borderRadius: shapes.xl,
      borderWidth: 1.5,
      overflow: 'hidden',
      marginBottom: 22,
      shadowColor: '#1A3A34',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 10,
      elevation: 2,
      backgroundColor: theme.card,
      borderColor: theme.border,
    },
    imageContainer: {
      width: '100%',
      height: 210,
      position: 'relative',
      backgroundColor: '#E5E7EB',
    },
    image: {
      width: '100%',
      height: '100%',
    },
    topBadgesRow: {
      position: 'absolute',
      top: 14,
      left: 14,
      right: 14,
      flexDirection: 'row',
      alignItems: 'center',
    },
    exclusiveBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#14352D',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: shapes.full,
      marginRight: 8,
    },
    exclusiveDot: {
      color: '#52D1A8',
      fontSize: 10,
    },
    exclusiveText: {
      color: '#FFFFFF',
      fontWeight: '700',
      fontSize: 12,
      letterSpacing: 0.2,
    },
    exclusivePercent: {
      color: '#E1E3E1',
      fontWeight: '600',
      fontSize: 12,
    },
    photoCountBadge: {
      position: 'absolute',
      bottom: 12,
      right: 14,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.94)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: shapes.full,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    cameraIcon: {
      marginRight: 4,
    },
    photoCountText: {
      color: theme.text,
      fontWeight: '700',
      fontSize: 12,
    },
    content: {
      padding: 20,
    },
    titleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 6,
    },
    title: {
      flex: 1,
      fontFamily: Platform.select({
        ios: 'Georgia',
        android: 'serif',
        default: 'serif',
      }),
      fontSize: 22,
      fontWeight: '700',
      letterSpacing: -0.3,
      lineHeight: 28,
      color: theme.text,
    },
    address: {
      fontSize: 15,
      fontWeight: '600',
      lineHeight: 22,
      marginBottom: 10,
      color: theme.textSecondary,
    },
    listedBy: {
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
      marginBottom: 10,
      color: theme.textSecondary,
    },
    specsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      marginBottom: 16,
    },
    specText: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.textSecondary,
    },
    specDot: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.textSecondary,
    },
    financialRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      paddingVertical: 4,
      marginBottom: 18,
    },
    priceCol: {
      flex: 1,
    },
    price: {
      fontSize: 24,
      fontWeight: '800',
      letterSpacing: -0.5,
      marginBottom: 2,
      color: theme.primary,
    },
    actionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    primaryAction: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      height: 48,
      borderRadius: shapes.md,
      marginRight: 10,
      backgroundColor: theme.primary,
    },
    actionBtnIcon: {
      marginRight: 6,
    },
    primaryActionText: {
      color: theme.onPrimary,
      ...typography.labelMD,
      fontSize: 15,
      fontWeight: '600',
    },
    secondaryAction: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      height: 48,
      borderRadius: shapes.md,
      borderWidth: 1,
      backgroundColor: theme.surfaceContainerLow,
      borderColor: theme.outlineVariant,
    },
    secondaryActionText: {
      ...typography.labelMD,
      fontSize: 15,
      fontWeight: '600',
      color: theme.text,
    },
  }),
  iconColorText: theme.text,
  iconColorPrimaryText: theme.onPrimary,
});
