/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/+not-found.styles`; params?: Router.UnknownInputParams; } | { pathname: `/agency.styles`; params?: Router.UnknownInputParams; } | { pathname: `/agency`; params?: Router.UnknownInputParams; } | { pathname: `/create-agency.styles`; params?: Router.UnknownInputParams; } | { pathname: `/create-agency`; params?: Router.UnknownInputParams; } | { pathname: `/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in.styles`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/agency.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/create-agency.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/index.auth.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/index.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/sign-in.test`; params?: Router.UnknownInputParams; } | { pathname: `/property/[id].styles`; params?: Router.UnknownInputParams; } | { pathname: `/property/__tests__/propertyDetail.attribution.test`; params?: Router.UnknownInputParams; } | { pathname: `/property/__tests__/propertyDetail.test`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/property/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/+not-found.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/agency.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/agency`; params?: Router.UnknownOutputParams; } | { pathname: `/create-agency.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/create-agency`; params?: Router.UnknownOutputParams; } | { pathname: `/index.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-in.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/agency.test`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/create-agency.test`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/index.auth.test`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/index.test`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/sign-in.test`; params?: Router.UnknownOutputParams; } | { pathname: `/property/[id].styles`; params?: Router.UnknownOutputParams; } | { pathname: `/property/__tests__/propertyDetail.attribution.test`; params?: Router.UnknownOutputParams; } | { pathname: `/property/__tests__/propertyDetail.test`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/property/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/+not-found.styles${`?${string}` | `#${string}` | ''}` | `/agency.styles${`?${string}` | `#${string}` | ''}` | `/agency${`?${string}` | `#${string}` | ''}` | `/create-agency.styles${`?${string}` | `#${string}` | ''}` | `/create-agency${`?${string}` | `#${string}` | ''}` | `/index.styles${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/sign-in.styles${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/__tests__/agency.test${`?${string}` | `#${string}` | ''}` | `/__tests__/create-agency.test${`?${string}` | `#${string}` | ''}` | `/__tests__/index.auth.test${`?${string}` | `#${string}` | ''}` | `/__tests__/index.test${`?${string}` | `#${string}` | ''}` | `/__tests__/sign-in.test${`?${string}` | `#${string}` | ''}` | `/property/[id].styles${`?${string}` | `#${string}` | ''}` | `/property/__tests__/propertyDetail.attribution.test${`?${string}` | `#${string}` | ''}` | `/property/__tests__/propertyDetail.test${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/+not-found.styles`; params?: Router.UnknownInputParams; } | { pathname: `/agency.styles`; params?: Router.UnknownInputParams; } | { pathname: `/agency`; params?: Router.UnknownInputParams; } | { pathname: `/create-agency.styles`; params?: Router.UnknownInputParams; } | { pathname: `/create-agency`; params?: Router.UnknownInputParams; } | { pathname: `/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in.styles`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/agency.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/create-agency.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/index.auth.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/index.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/sign-in.test`; params?: Router.UnknownInputParams; } | { pathname: `/property/[id].styles`; params?: Router.UnknownInputParams; } | { pathname: `/property/__tests__/propertyDetail.attribution.test`; params?: Router.UnknownInputParams; } | { pathname: `/property/__tests__/propertyDetail.test`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/property/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/property/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
